Indexer:
  BlockInterval: '10s'
  PoolSize: 2
  BlockPtr: 8233707
Network:
  ChainId: 5
  NativeAsset:
    Name: 'Ethereum'
    Symbol: 'ETH'
    Decimals: 18
    MockAddress: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE'
  Node:
    Api: 'https://rpc.ankr.com/eth_goerli'
Wallet:
  Private: ''
  Address: ''
Contracts:
  ETHA:
    Clipper: '0x7Dfd4834d5731dC45da97E561931dFBEF0dCc2FA'
    GemJoinAdapter: '0x03F6141bFda8e2925b46BB62a1Aa0Aeac904FfEB'
  ETHB:
    Clipper: '0x92a8F182E27692f8EcCc08C80642Ad24735DB4bf'
    GemJoinAdapter: '0x5b844f6276582ed8bB6D47A3B0c7001D1F47aAED'
Processor:
  MinProfitPercentage: 1.025
  MinLotZarValue: 0
  MaxLotZarValue: 1000000