Indexer:
  BlockInterval: '10s'
  PoolSize: 2
  BlockPtr: 8233707
Network:
  NativeAsset:
    Name: 'Ethereum'
    Symbol: 'ETH'
    Decimals: 18
    MockAddress: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE'
  Node:
    Api: 'https://rpc.ankr.com/eth_goerli'
Wallet:
  Private: ''
  Address: '0xb94c551347D04DA5a815844f464AD48918E48686'
Contracts:
  ETHAClipper: ''
  ETHBClipper: ''
Processor:
  MinProfitPercentage: 1.025
  MinLotZarValue: 0
  MaxLotZarValue: 1000000