version: "3.8"

services:
  postgres:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auction-keeper
    ports:
      - "5432:5432"
volumes:
  data:
